# Generated by Django 4.2.4 on 2023-08-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1023, verbose_name="name")),
            ],
            options={
                "verbose_name_plural": "factories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sprocket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teeth", models.IntegerField(verbose_name="teeth")),
                (
                    "pitch_diameter",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="pitch diameter"
                    ),
                ),
                (
                    "outside_diameter",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="pitch diameter"
                    ),
                ),
                ("pitch", models.IntegerField(verbose_name="pitch")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.factory"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FactoryProductionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sprocket_production_actual",
                    models.IntegerField(verbose_name="current sprocket production"),
                ),
                (
                    "sprocket_production_goal",
                    models.IntegerField(verbose_name="sprocket production goal"),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.factory"
                    ),
                ),
            ],
        ),
    ]
